### ISSUE TITLE
this repo does not contain code for paper #2 with enhanced features

### ISSUE THREAD

**Issue by zichaow** [vijini/MWP_generation#1]
hello,

I think this repo is the code for the first paper "A Multi-language Platform for Generating Algebraic Mathematical Word Problems"

It does not contain the code for the second paper "Multi-lingual Mathematical Word Problem Generation using Long Short Term Memory Networks with Enhanced Input Features", contrary to what readme describes.

The script `char_POS.py` performs POS only after the MWP is generated; this is described in the first paper, not the second. See line https://github.com/vijini/MWP_generation/blob/3b7c68ca5355c9187382a806d6db239ea43149d0/char_POS.py#L115

Could you update the repo to include code for the second paper also? Much appreciated!

**Comment by vijini** [comment]
Please refer the attention.py file for the updated code.
